
train_path: 'F:\\VOCdevkit\\VOC2012\\JPEGImages'
logs_path: "./logs/"
checkpoints_path: './checkpoints/'
saved_models: './saved_models'

cuda: True

exp_name: 2
secret_size: 100
num_steps: 140000
batch_size: 4
lr: 0.0001
l2_loss_scale: 2
l2_loss_ramp: 15000
l2_edge_gain: 10
l2_edge_ramp: 10000
l2_edge_delay: 80000
lpips_loss_scale: 1.5
lpips_loss_ramp: 15000
secret_loss_scale: 1.5
secret_loss_ramp: 1
G_loss_scale: 0.5
G_loss_ramp: 15000
borders: 'white' # choices=['no_edge','black','random','randomrgb','image','white']
y_scale: 1
u_scale: 100
v_scale: 100
no_gan: True
rnd_trans: 0.1
rnd_bri: 0.3
rnd_noise: 0.02
rnd_sat: 1.0
rnd_hue: 0.1
contrast_low: 0.5
contrast_high: 1.5
jpeg_quality: 50
no_jpeg: True
rnd_trans_ramp: 10000
rnd_bri_ramp: 1000
rnd_sat_ramp: 1000
rnd_hue_ramp: 1000
rnd_noise_ramp: 1000
contrast_ramp: 1000
jpeg_quality_ramp: 1000
no_im_loss_steps: 1500
pretrained: None
